export const PAGE_LOADING_TIMEOUT_SECONDS = 3;

export const FADE_ANIMATION_DURATION_NUMBER = 600;
export const FADE_ANIMATION_DURATION_CLASS = 'duration-600';

export const ANIMATION_SHORT_DELAY_NUMBER = 100;
export const ANIMATION_SHORT_DELAY_CLASS = 'delay-100';

export const ANIMATION_MID_DELAY_NUMBER = 600;
export const ANIMATION_MID_DELAY_CLASS = 'delay-600';

export const ANIMATION_LONG_DELAY_NUMBER = 1000;
export const ANIMATION_LONG_DELAY_CLASS = 'delay-1000';
