/**
 * Animation constants for Kiosk 3 Custom Interactive screens
 */

/**
 * Z-index stacking order for layered elements.
 * Use these constants to maintain consistent z-index hierarchy.
 */
export const Z_INDEX = {
  /** Background layer (morphing diamond video) */
  BACKGROUND: 0,
  /** Carousel content layer */
  CAROUSEL: 10,
  /** Demo overlay (highest priority) */
  OVERLAY: 9999,
} as const;

/**
 * Slide identifiers for carousel navigation.
 * These IDs are generated by the CMS mapper and used for conditional rendering.
 */
export const SLIDE_ID = {
  SLIDE_1: 'slide-1',
  SLIDE_2: 'slide-2',
  SLIDE_3: 'slide-3',
  SLIDE_4: 'slide-4',
  SLIDE_5: 'slide-5',
  SLIDE_6: 'slide-6',
} as const;

export type SlideId = (typeof SLIDE_ID)[keyof typeof SLIDE_ID];

/**
 * Framer Motion transition configurations.
 * Standardized easing curves and durations for consistent animations.
 */
export const TRANSITIONS = {
  /** Standard carousel transitions (slides, diamonds) */
  CAROUSEL: { duration: 0.6, ease: [0.3, 0, 0.4, 1] as const },
  /** Fade transitions (initial state, overlays) */
  FADE: { duration: 0.5, ease: [0.3, 0, 0.6, 1] as const },
  /** Slide content (text, bullets) with delay for stagger effect */
  SLIDE_CONTENT: { delay: 0.2, duration: 0.4, ease: [0.3, 0, 0.6, 1] as const },
  /** SVG decorative elements scale animation */
  SVG_SCALE: { duration: 0.6, ease: [0.3, 0, 0.6, 1] as const },
} as const;

/**
 * Morphing diamond animation states.
 * The background video transforms from full-screen to a carousel slide diamond.
 *
 * Coordinate system:
 * - x/y: Translate values in pixels (negative = left/up)
 * - scale: Size multiplier (1 = original, 0.332 = ~1/3 size)
 * - Video positioning: Counter-scales to maintain visual consistency
 */
export const MORPHING_DIAMOND = {
  /** Initial state: Full-screen centered background */
  BACKGROUND: {
    opacity: 1,
    scale: 1,
    x: 0,
    y: 0,
  },
  /** Carousel state: Scaled down and positioned as first slide */
  CAROUSEL: {
    opacity: 1,
    scale: 0.332,
    x: -1095,
    y: -875,
  },
  /** Exit state: Moves diagonally off-screen with fade */
  EXIT: {
    opacity: 0,
    scale: 0.332,
    x: -1116,
    y: -896,
  },
  /** Video horizontal offset in background state (px) */
  VIDEO_LEFT_BACKGROUND: 480,
  /** Video horizontal offset in carousel state (px) */
  VIDEO_LEFT_CAROUSEL: 0,
  /** Video scale multiplier in background state */
  VIDEO_SCALE_BACKGROUND: 1.7,
  /** Video scale multiplier in carousel state */
  VIDEO_SCALE_CAROUSEL: 1.4,
} as const;

/**
 * Primary diamond (video/image) positioning classes by slide variant.
 * Different slides have different layouts requiring repositioning.
 */
export const PRIMARY_DIAMOND_POSITIONS = {
  /** Default position for slides 1 & 4 */
  DEFAULT:
    'absolute left-[700px] bottom-[1120px] h-[830px] w-[830px] rotate-45 overflow-hidden rounded-[90px] shadow-[0_30px_90px_rgba(0,0,0,0.35)]',
  /** Larger, repositioned for slides 2 & 5 */
  SLIDE_2_5:
    'absolute left-[510px] bottom-[670px] h-[1200px] w-[1200px] rotate-45 overflow-hidden rounded-[90px] shadow-[0_30px_90px_rgba(0,0,0,0.35)]',
  /** Lower position for slides 3 & 6 */
  SLIDE_3_6:
    'absolute left-[340px] bottom-[340px] h-[1130px] w-[1130px] rotate-45 overflow-hidden rounded-[90px] shadow-[0_30px_90px_rgba(0,0,0,0.35)]',
} as const;

/**
 * Secondary diamond (decorative image) positioning classes by slide variant.
 */
export const SECONDARY_DIAMOND_POSITIONS = {
  /** Default position for most slides */
  DEFAULT:
    'absolute left-[1380px] bottom-[400px] h-[880px] w-[880px] rotate-45 overflow-hidden rounded-[80px] shadow-[0_24px_70px_rgba(0,0,0,0.32)]',
  /** Higher position for slides 3 & 6 */
  SLIDE_3_6:
    'absolute left-[1390px] bottom-[1150px] h-[800px] w-[800px] rotate-45 overflow-hidden rounded-[80px] shadow-[0_24px_70px_rgba(0,0,0,0.32)]',
} as const;

/**
 * Diamond entry/exit animation states.
 * Diamonds scale from 0 to 1 on entry, then move diagonally on exit.
 */
export const DIAMOND_ANIMATIONS = {
  ENTRY: {
    /** Final state: Fully visible at natural position */
    animate: { opacity: 1, scale: 1, x: 0, y: 0 },
    /** Exit state: Fade out while moving diagonally */
    exit: { opacity: 0, scale: 1, x: -21, y: -21 },
    /** Initial state: Hidden, scaled to 0 */
    initial: { opacity: 0, scale: 0, x: 0, y: 0 },
  },
} as const;

/**
 * SVG decorative diamond animations.
 * Background decorative elements that scale in and fade with slides.
 */
export const SVG_ANIMATIONS = {
  /** Container animation (fade + vertical movement) */
  CONTAINER: {
    animate: { opacity: 1, y: 0 },
    exit: { opacity: 0, y: -30 },
    initial: { opacity: 0, y: 0 },
  },
  /** Individual SVG scale animation */
  SCALE: {
    animate: { scale: 1 },
    initial: { scale: 0 },
  },
} as const;

/**
 * Computes the animation state for the morphing diamond background.
 *
 * @param showCarousel - Whether carousel is visible
 * @param carouselIndex - Current carousel slide index (0-based)
 * @param isCarouselExiting - Whether current slide is exiting
 * @returns Animation state object with opacity, scale, x, y
 */
export function getMorphingDiamondAnimation(
  showCarousel: boolean,
  carouselIndex: number,
  isCarouselExiting: boolean
): { opacity: number; scale: number; x: number; y: number } {
  if (carouselIndex === 0 && isCarouselExiting) {
    return MORPHING_DIAMOND.EXIT;
  }
  if (showCarousel) {
    return MORPHING_DIAMOND.CAROUSEL;
  }
  return MORPHING_DIAMOND.BACKGROUND;
}

/**
 * Gets the CSS class for primary diamond based on current slide.
 *
 * @param slideId - Slide identifier (use SLIDE_ID constants)
 * @returns Tailwind CSS class string for positioning
 */
export function getPrimaryDiamondClass(slideId: string): string {
  if (slideId === SLIDE_ID.SLIDE_2 || slideId === SLIDE_ID.SLIDE_5) {
    return PRIMARY_DIAMOND_POSITIONS.SLIDE_2_5;
  }
  if (slideId === SLIDE_ID.SLIDE_3 || slideId === SLIDE_ID.SLIDE_6) {
    return PRIMARY_DIAMOND_POSITIONS.SLIDE_3_6;
  }
  return PRIMARY_DIAMOND_POSITIONS.DEFAULT;
}

/**
 * Gets the CSS class for secondary diamond based on current slide.
 *
 * @param slideId - Slide identifier (use SLIDE_ID constants)
 * @returns Tailwind CSS class string for positioning
 */
export function getSecondaryDiamondClass(slideId: string): string {
  if (slideId === SLIDE_ID.SLIDE_3 || slideId === SLIDE_ID.SLIDE_6) {
    return SECONDARY_DIAMOND_POSITIONS.SLIDE_3_6;
  }
  return SECONDARY_DIAMOND_POSITIONS.DEFAULT;
}

/**
 * Determines which decorative SVG variant to show based on slide ID.
 * Different slides have different background SVG patterns for visual variety.
 *
 * @param slideId - Slide identifier (use SLIDE_ID constants)
 * @returns SVG variant identifier for DecorativeSVGGroup component
 */
export function getDecorativeSVGVariant(slideId: string): 'default' | 'slide-2-5' | 'slide-3-6' {
  if (slideId === SLIDE_ID.SLIDE_2 || slideId === SLIDE_ID.SLIDE_5) {
    return 'slide-2-5';
  }
  if (slideId === SLIDE_ID.SLIDE_3 || slideId === SLIDE_ID.SLIDE_6) {
    return 'slide-3-6';
  }
  return 'default';
}
